#!/bin/bash

first=$1
shift
rest=$@

if test -f "./scripts/$first.sh"; then
  echo "Running $first"
  bash "./scripts/$first.sh" $@
else
  echo "Unknown script. Run one of the following"
  echo ""
  ls ./scripts | sed 's/\(.*\)\.sh/- \1/'
fi